spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board_test?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:init.sql

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: d52451887cdd45742cfeed8f30599754834d6035e3001d49a76d989042772500
  exp: 10800

store:
  base-path: /tmp/test-store/

free-board:
  path: board/
  deleted-path: boardDeleted/
  volume: 2097152

gallery-board:
  thumbnail:
    path: thumbnail/
  picture:
    path: gallery/
    deleted-path: galleryDeleted/
    volume: 1048576

app:
  cors:
    allowed-origins: "http://localhost:5173"
  cookie:
    secure: false
